import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import { Refine, GitHubBanner } from "@refinedev/core";
import { DevtoolsProvider } from "@providers/devtools";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import {
  ThemedTitleV2,
  useNotificationProvider,
  RefineSnackbarProvider,
} from "@refinedev/mui";
import routerProvider from "@refinedev/nextjs-router";

import { AppIcon } from "@components/app-icon";
import { authProviderClient } from "@providers/auth-provider/auth-provider.client";
import { dataProvider } from "@providers/data-provider";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { Header } from "@components/header";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <ColorModeContextProvider defaultMode={defaultMode}>
              <RefineSnackbarProvider>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    authProvider={authProviderClient}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    resources={[
                      {
                        name: "Category",
                        list: "/Category",
                        create: "/Category/create",
                        edit: "/Category/edit/:id",
                        show: "/Category/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "EventType",
                        list: "/EventType",
                        create: "/EventType/create",
                        edit: "/EventType/edit/:id",
                        show: "/EventType/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "Group",
                        list: "/Group",
                        create: "/Group/create",
                        edit: "/Group/edit/:id",
                        show: "/Group/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "Object",
                        list: "/Object",
                        create: "/Object/create",
                        edit: "/Object/edit/:id",
                        show: "/Object/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "Barcode",
                        list: "/Barcode",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "Event",
                        list: "/Event",
                        create: "/Event/create",
                        edit: "/Event/edit/:id",
                        show: "/Event/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                      {
                        name: "User",
                        list: "/User",
                        create: "/User/create",
                        edit: "/User/edit/:id",
                        show: "/User/show/:id",
                        meta: {
                          canDelete: true,
                        },
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "zGRw11-BzVqrU-CuJQmq",
                      title: { text: "ObjectTrack", icon: <AppIcon /> },
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </RefineSnackbarProvider>
            </ColorModeContextProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
