-- =========================================================
-- 0) (Optional) Helpful extensions (Supabase usually has these)
-- =========================================================
-- create extension if not exists pgcrypto;

-- =========================================================
-- 1) Core tables
-- =========================================================

create table public.groups (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text,
  created_at  timestamptz not null default now()
);

create table public.categories (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  created_at  timestamptz not null default now()
);

create table public.objects (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  category_id bigint references public.categories(id) on delete restrict,
  model       text,
  created_at  timestamptz not null default now()
);

create table public.event_types (
  id    bigint generated by default as identity primary key,
  label text not null unique
);

-- =========================================================
-- 2) User profiles (links to Supabase Auth)
-- =========================================================
create table public.user_profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  group_id   bigint references public.groups(id) on delete set null,

  -- your fields
  last_name  text,
  first_name text,
  title      text,
  city       text,
  province   text,
  country    text,
  zipcode    text,
  phone      text,
  wechat_id  text,

  email      text, -- optional mirror (auth.users.email exists)
  created_at timestamptz not null default now()
);

create index idx_user_profiles_group_id on public.user_profiles(group_id);
create unique index ux_user_profiles_wechat_id on public.user_profiles(wechat_id)
  where wechat_id is not null;

-- =========================================================
-- 3) Events (group-shared)
-- =========================================================
create table public.events (
  id         bigint generated by default as identity primary key,

  group_id   bigint not null references public.groups(id) on delete cascade,
  object_id  bigint not null references public.objects(id) on delete cascade,
  event_type_id bigint not null references public.event_types(id) on delete restrict,

  e_from     uuid references public.user_profiles(id) on delete set null,
  e_to       uuid references public.user_profiles(id) on delete set null,

  extra      jsonb,
  created_at timestamptz not null default now()
);

create index idx_events_group_id      on public.events(group_id);
create index idx_events_object_id     on public.events(object_id);
create index idx_events_event_type_id on public.events(event_type_id);
create index idx_events_from          on public.events(e_from);
create index idx_events_to            on public.events(e_to);

-- =========================================================
-- 4) Auto-create profile row on signup
-- =========================================================
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  insert into public.user_profiles (id, email, created_at)
  values (new.id, new.email, now())
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_auth_user();

-- =========================================================
-- 5) Helper: current user's group id
-- =========================================================
create or replace function public.current_group_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select up.group_id
  from public.user_profiles up
  where up.id = auth.uid()
$$;

-- =========================================================
-- 6) RLS Policies (Option 2: group-wide visibility)
-- =========================================================

-- ---- groups: readable by members, typically not directly writable by clients
alter table public.groups enable row level security;

create policy "read group (member)"
on public.groups
for select
using (id = public.current_group_id());


-- ---- user_profiles: group members can read each other, user can update self
alter table public.user_profiles enable row level security;

create policy "read profiles in my group"
on public.user_profiles
for select
using (group_id is not null and group_id = public.current_group_id());

create policy "update own profile"
on public.user_profiles
for update
using (id = auth.uid())
with check (id = auth.uid());

-- Optional: prevent random inserts from client (trigger handles it).
-- If you *do* allow inserts (e.g. admin UI), constrain strongly:
-- create policy "insert own profile only"
-- on public.user_profiles
-- for insert
-- with check (id = auth.uid());


-- ---- objects/categories/event_types: choose your sharing model
-- Here: readable to authenticated users; writes locked down (common for lookup tables)
alter table public.categories enable row level security;
alter table public.objects enable row level security;
alter table public.event_types enable row level security;

create policy "read categories"
on public.categories for select
using (auth.role() = 'authenticated');

create policy "read objects"
on public.objects for select
using (auth.role() = 'authenticated');

create policy "read event types"
on public.event_types for select
using (auth.role() = 'authenticated');


-- ---- events: everyone in my group can read; inserts/updates restricted to same group
alter table public.events enable row level security;

create policy "read events in my group"
on public.events
for select
using (group_id = public.current_group_id());

create policy "insert events in my group (must be sender)"
on public.events
for insert
with check (
  group_id = public.current_group_id()
  and e_from = auth.uid()
);

create policy "update events in my group (sender only)"
on public.events
for update
using (
  group_id = public.current_group_id()
  and e_from = auth.uid()
)
with check (
  group_id = public.current_group_id()
  and e_from = auth.uid()
);

create policy "delete events in my group (sender only)"
on public.events
for delete
using (
  group_id = public.current_group_id()
  and e_from = auth.uid()
);
