-- Align transfer_requests.id with the live identity generation strategy.
-- This is a NOOP when the column is already GENERATED BY DEFAULT AS IDENTITY.
do $$
begin
  if exists (
    select 1
    from pg_attribute
    where attrelid = 'public.transfer_requests'::regclass
      and attname = 'id'
      and attidentity = 'a'
      and not attisdropped
  ) then
    alter table public.transfer_requests
      alter column id set generated by default;
  end if;
end;
$$;
